# Generated by Django 5.1.3 on 2024-11-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_alter_memomodel_content_alter_memomodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memomodel',
            options={'verbose_name': 'メモ', 'verbose_name_plural': 'メモ一覧'},
        ),
    ]
