# Generated by Django 5.1.3 on 2024-11-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_memomodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memomodel',
            name='public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
