# Generated by Django 5.1.3 on 2024-11-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_memomodel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='memomodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
