# Generated by Django 5.1.3 on 2024-11-24 00:35

import memo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0006_memomodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memomodel',
            name='slug',
            field=models.SlugField(default=memo.models.slug_maker, max_length=20, unique=True),
        ),
    ]
